# Generated by Django 5.2.5 on 2025-12-14 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_topics', to='post.post')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
